### ISSUE TITLE
LOW PRIORITY: Checks that dto passed to Create() and then GenerateScore/Pickup/etc() is safe

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo-unity#118]
LOW PRIORITY: Checks that dto passed to Create() and then GenerateScore/Pickup/etc() is safe

**Comment by CelineBoudier** [comment]
we should be consistent with labels vs naming - we have a "low priority" label

**Comment by mrniket** [comment]
Not a priority, closing this issue
