### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#17]
In the [travis](https://github.com/ocadotechnology/aimmo-unity/tree/travis) branch we have written quite a few unit tests. However, run time behaviour is just partially tested since in Unity the Editor mode and the Play mode behave very differently. That is why we should write some integration tests before merging #2. The Unity Test Tools package provides [support for it](https://bitbucket.org/Unity-Technologies/unitytesttools/wiki/IntegrationTestsRunner).

**Comment by mrniket** [comment]
not relevant.
