### ISSUE TITLE
Future terrain skin for MMO

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo-unity#173]
Design a brief and quick future skin for the MMO (which can be further used in the trailer).

**Comment by mariaFernando** [comment]
![floors.jpg](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/a9a34fde-fa3f-44e6-8826-6a05727202f7)
![dee_and_boxes.jpg](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/6780e00b-b3ad-4efa-811f-3dc7438dab93)
