### ISSUE TITLE
Design avatar marker

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo-unity#190]
So I can keep track of my avatar's progress in the game

**Comment by mariaFernando** [comment]
![Screen Shot 2018-03-06 at 11.49.10.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/8a53e2f2-4b1b-4daf-8d51-e595e5547e90)
![Screen Shot 2018-03-06 at 11.49.38.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/136107de-c826-458a-b174-9ef8dcca044c)
