### ISSUE TITLE
Level builder - basic test suite

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#20]
Test the exporting functionality and the options in the editor. Most of it should be easy to test, since both the level builder tool runs in Editor mode just like the unity tests tool. The only tricky part will be the 'try' option added in #19.

**Comment by danalex97** [comment]
Looking on how to generate clicks might be of interest here as well.

**Comment by mrniket** [comment]
We aren't doing this anymore, not relevant.
