### ISSUE TITLE
The game looks pixelated at some zoom sizes

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo-unity#208]
investigate the trade off between perfect anti-aliasing and frame rate

**Comment by j4mesholland** [comment]
@mariaFernando is this something we need to fix for September?

**Comment by mariaFernando** [comment]
I wouldn't say this is an important fix (I personally didn't notice it much and I think we can simply cap the zoom range)

**Comment by mrniket** [comment]
Not an issue anymore since we have capped the zoom size
