### ISSUE TITLE
Change font on compass to Museo Sans

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo-unity#216]
So that it matches with the wider game UI

**Comment by mariaFernando** [comment]
![Screen Shot 2018-07-04 at 16.14.31.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/f0d2815c-b200-43e2-85ea-24a9dbf90a2d)

**Comment by mariaFernando** [comment]
![Screen Shot 2018-07-04 at 16.15.38.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/c58d34d3-06e4-448a-8f01-99c3d2cc274b)

**Comment by j4mesholland** [comment]
Looks good to me

**Comment by mariaFernando** [comment]
@CelineBoudier @OlafSzmidt @mrniket @riaJha97 any comment?

**Comment by riaJha97** [comment]
I like it :)

**Comment by CelineBoudier** [comment]
same :) Something that might be done as well: mark the North like on some compasses, so that it makes it easier later for international students?

**Comment by mariaFernando** [comment]
![Screen Shot 2018-07-05 at 11.15.38.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/513fe480-e153-44f9-9a5a-c12084ae31e8)

@CelineBoudier something like this?

**Comment by CelineBoudier** [comment]
Yes for instance :)

**Comment by mariaFernando** [comment]
@j4mesholland what do you think? :)

**Comment by j4mesholland** [comment]
Yes, that works. Could you also try something within the cross in the middle?

**Comment by j4mesholland** [comment]
Yes, that works really well :-)

**Comment by mariaFernando** [comment]
Thanks! @CelineBoudier anything to add? :)

**Comment by CelineBoudier** [comment]
No I like the second one more as well :)

**Comment by j4mesholland** [comment]
Fixed issue with transparency in .PNG export
