### ISSUE TITLE
Beautifying the edge of the map

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo-unity#231]
Right now, the map falls into a weird horizon.

**Comment by mariaFernando** [comment]
The best way might be to just generate the terrain with a fixed increment relative to the actual map size, which would depend on how far the camera zooms out (?)

**Comment by mariaFernando** [comment]
Will try to add a terrain under the existing one to cover the skybox

**Comment by mariaFernando** [comment]
If the solution is to add a terrain under the existing one, should I just create the prefab and leave the creation up to development? 
Will it have a fixed size or be calculated from the map size?
Also, does the camera movement have any cap at the moment outside MoveCamera.cs?
@mrniket @OlafSzmidt

**Comment by j4mesholland** [comment]
Niket and Mafalda to discuss
