### ISSUE TITLE
Map twitches and camera can escape the map

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo-unity#247]
**Describe the bug**
Camera twitches when you try to drag the map off the screen, also if you time it right the map will go off the screen, so the camera goes out of its boundary.

**To Reproduce**
1. Go into an aimmo game
2. Drag aimmo as far in one direction as you can
3. You'll see it start to twich rapidly
4. if you let go at the right time, you'll be able to get the camera to go as far away from the map as you want.

**Expected behavior**
Map does not twitch, camera stays inside of it's bounds.

**Comment by mrniket** [comment]
The switch to Babylon means that this is not an issue anymore
