### ISSUE TITLE
WebGL export does not run on computers without hardware acceleration

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo-unity#250]
**Describe the bug**
Aimmo Unity does not run on web browsers where hardware acceleration is not available.

**To Reproduce**
Steps to reproduce the behaviour:
1. On Google Chrome, disable hardware acceleration here: chrome://settings/system
2. Go on the aimmo game page
3. See that the game starts but the unity game view does not load

**Expected behaviour**
The game view should load.

**Screenshots**
See https://github.com/ocadotechnology/aimmo/issues/889

**Additional context**
See https://github.com/ocadotechnology/aimmo/issues/889

**Comment by OlafSzmidt** [comment]
https://wevideo.zendesk.com/hc/en-us/articles/225259448-How-to-enable-WebGL
https://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser
https://caniuse.com/#feat=webgl

Are you sure this is possible?

**Comment by mrniket** [comment]
The switch to Babylon means that this is not an issue anymore. The game runs now on computers that can't use hardware acceleration, just really slowly. Better than a black screen!
