### ISSUE TITLE
Build errors and granularity

### ISSUE THREAD

**Issue by danalex97** [ocadotechnology/aimmo-unity#26]
When trying to build to WebGL the project, the build can't be executed. The issues is the import of UnityEditor namespace inside the main assembly. This can be solved by removing some imports.

Another problem with the build is that all the files are included in the build, whereas the tool for level generation and the tests, as well as the test framework folder, should not be included at all.

**Comment by danalex97** [comment]
Since @OlafSzmidt begin working on putting the whole aimmo together, I shall explain this in more detail. @ramonfmir maybe you can also take a look.

When I tried [building](https://docs.unity3d.com/Manual/webgl-building.html),  I did not work. (yey!) 
I think @ramonfmir gave details on how to build in the readme. To get a traceback one can [use the command line tool for building](https://github.com/ocadotechnology/aimmo-unity/blob/travis/UnityProject/Assets/Editor/WebGLBuilder.cs)...

The problem(probably) is that the build does not like "using UnityEditor;" - or anything related - inside the scripts folder. An example is  `aimmo-unity/UnityProject/Assets/Scripts/LevelBuilder/SpriteGeneratorBuilder.cs`. Removing all of those would allow building again.

Another problem(not crucial) is that the build takes ages -- as in 5 minutes or something, much more than before. That is because we build the stuff in editor folder. A workaround that I think it works is  using:

```csharp
#if UNITY_EDITOR
[...] // the whole file 
#endif
```

in all the editor files that should not be built. A better solution would be probably possible using the command line build tool smarter(have no idea how) or actually separate the repo(have no idea how).

**Comment by OlafSzmidt** [comment]
@ramonfmir Did you write any instructions on how to build anywhere? Can't seem to find it.

**Comment by OlafSzmidt** [comment]
Running the command line tool for building gets stuck on this:

`Registered platform support modules in: 0.0496501s.
Native extension for OSXStandalone target not found
Native extension for WindowsStandalone target not found
Native extension for LinuxStandalone target not found
Native extension for WebGL target not found
Native extension for SamsungTV target not found
Native extension for Tizen target not found
Native extension for iOS target not found
Native extension for Android target not found
[0914/114053:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.`

**Comment by ramonfmir** [comment]
@OlafSzmidt  No, I actually completely omitted that part. But you should be able to build just by going to `File > Build Settings` and selecting the WebGL option (tick `Development Build`, it will be faster).  

However, @danalex97 is right, last time I checked, all the editor stuff didn't allow us to build. And I completely agree with his suggestion of using macros. I have seen lots of Unity code that use things like that to distinguish between editor code and code to be built.

**Comment by OlafSzmidt** [comment]
So trying to build on `master`, as I'm unsure about what the `travis` branch is here for... returns this:

![screenshot from 2017-09-14 13-21-35](https://user-images.githubusercontent.com/22431381/30429493-a5ba10c2-994f-11e7-8faf-cf41c3add0ca.png)

Is this the same errors that you guys were getting that need to be fixed?

Using the command line with the log files returns an error for SUID sandbox from Chromium. I tried installing it, changing permissions, setting root as owner to `google-sandbox`, removing Google Chrome (as it was known it interefered). Nothing worked. In different applications this is only treated as a warning - I don't know if we need it for Unity.

**Comment by ramonfmir** [comment]
I believe this errors are all related with the editor code and hopefully will disappear when you do the `if UNITY_EDITOR` thing. Something you can do to test if it will work is removing all the editor tool code and just keep the main functionality. Then try to build and see if that works.

**Comment by OlafSzmidt** [comment]
The namespace issue is gone with [platform dependent compilation](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html). Good call. 

https://github.com/ocadotechnology/aimmo-unity/commit/00cdba691fe33a2a52d650470372cee674704f14

Does that solve this issue? Are we good to close? @ramonfmir @danalex97 

I will definitely open a new one because even the development build took close to 10 minutes for me, so that will be looked into.

**Comment by ramonfmir** [comment]
@OlafSzmidt link this issue with the PR that will come from the platform_dependant_compilation branch.

**Comment by OlafSzmidt** [comment]
I was going to do this; but was asking if there's anything else that needs to be done before I open a PR :) On it now.

**Comment by OlafSzmidt** [comment]
@ramonfmir Do you know what [this](https://github.com/danalex97/aimmo/tree/webgl) is? @danalex97 isn't here for a few days so probably won't respond.

**Comment by danalex97** [comment]
@OlafSzmidt  I saw this quite late. Is just the webGL/JS related stuff that I cherry-picked from Unity branch. I will try to make that work when I have more time.

**Comment by OlafSzmidt** [comment]
Perhaps dependant on #27.

**Comment by danalex97** [comment]
@OlafSzmidt Still not sure how we can do #27

**Comment by danalex97** [comment]
Can we deploy(by hand) at the moment?

**Comment by mrniket** [comment]
WebGL builds now, closing this issue.
