### ISSUE TITLE
Split the repository

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#27]
There are two different projects in this repository:
- The main one, which listens to the back-end and updates the scene accordingly.
- The level builder, which is an editor tool for designers to create levels.

It would be nice if we could split them into two different repositories. One of the problems is that we have intentionally made the level builder depend on the main one so that map features are added to the scene using the same code that will be used in the actual game. I was thinking about making it a git submodule but I'm not sure that's a good idea.

**Comment by mrniket** [comment]
We aren't doing this anymore, not relevant.
