### ISSUE TITLE
Level builder - error on save

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#31]
On ctr+s on the [improve_editor_ux](https://github.com/ocadotechnology/aimmo-unity/tree/improve_editor_ux) branch I get the following error:

`Timestamps (354) and assets (353) maps out of sync - repair failed`

**Comment by ramonfmir** [comment]
Look at this http://answers.unity3d.com/questions/236053/timestamps-566-and-assets-567-maps-out-of-sync.html @OlafSzmidt

**Comment by danalex97** [comment]
Maybe is related to the code below. We load an asset each frame. 

```C#
	public void Display()
	{
		[...]
		// Show controls image.
		controlsTexture = (Texture2D) Resources.Load("Images/controls");
                [...]
	}
```

**Comment by OlafSzmidt** [comment]
Came across this issue this morning. "Reimport all" fixed it, or just removing the `Library` folder in your repo. I'm almost certain this is because of unity versioning and not the code.

That being said I might be wrong.

**Comment by OlafSzmidt** [comment]
As the issue hasn't came back; I'm closing this issue.

**Comment by ramonfmir** [comment]
I read that this error can be solved by reimporting the project. So this is not really our issue but Unity's.
