### ISSUE TITLE
Level builder - error when opening the window

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#32]
On the [improve_editor_ux](https://github.com/ocadotechnology/aimmo-unity/tree/improve_editor_ux) branch when I open the editor window I get the following error:

`ArgumentException: Getting control 15's position in a group with only 15 controls when doing Repaint`

It all works afterwards.

**Comment by OlafSzmidt** [comment]
Fixed with 5c3d30a.
