### ISSUE TITLE
Level builder - 'Create level' button

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#35]
Forcing level designers to create the levels using our own button would be a good idea. First of all we wouldn't need to worry about dynamically adding the generators so that map features can be created. Instead this new scene that we control the creation of can have all the scripts (in the for of components) that we will need in the future. 

By doing this, the `ObjectController` won't need to worry about the `Level Builder Context` and instead just worry about moving game objects in the scenes, as it should be.

Also, it would be nice to have a drop down menu with the levels.

**Comment by OlafSzmidt** [comment]
Linked to #7.

**Comment by OlafSzmidt** [comment]
Proposed changes for this issue:

- Dropdown for levels instead of buttons being individual.
- New method in `GUI/Util/AssetController.cs` (possibly renamed to AssetFetcher soon). It will return the current numbers of levels created.
- Get that number in `LightControlMenu.cs` and increment it to create the new scene name.
- Then we can further work on calling `SetUp()` from issue #12.

**Comment by OlafSzmidt** [comment]
Dropdown implemented with https://github.com/ocadotechnology/aimmo-unity/commit/39503c638578e34df52a4b94422e03609f740047.

**Comment by OlafSzmidt** [comment]
Came across another issue (writing for self reference). When a scene is added along with `GameObject` components, the old scene that was open is not unloaded which will cause issues.

To do:

- Find a way of unloading old scenes.
- See if we are required to add the light as we add the scene or not.

**Comment by OlafSzmidt** [comment]
Scenes are now unloaded with https://github.com/ocadotechnology/aimmo-unity/commit/ae885aa004fbddcc5dc42519ae63e6a499de26be. Light will be required to be added with generating a new scene.

However... `EditorSceneManager.SaveScene()` is not working as expected. It saves the level to a file, but not the objects from the hierarchy (so on reopening of the scene we are back to a default setup).

**Comment by OlafSzmidt** [comment]
The saving issue fixed with #52. We still have to figure out how to set up the camera, lights and the scene properly.

**Comment by OlafSzmidt** [comment]
This is fixed with #55.
