### ISSUE TITLE
Level builder - make it clearer when you're moving the light

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#37]
Nowhere in the level builder it says that you're moving the light so sometimes it looks like the keys are broken. Think about something. 

This is not that simple though. It is a problem we have encountered throughout the process of building this editor tool. You can detect keys all the time but you can only modify the interface of the editor inside the `OnGUI()` method. The way Unity works, it will only be called when the mouse is over it, which might not lead to a great user experience.

**Comment by danalex97** [comment]
A workaround might be [doing click from script](http://answers.unity3d.com/questions/945299/how-to-trigger-a-button-click-from-script.html). The clicks will trigger OnGUI and redraw the GUI. We can register this as a callback for pressing the 'L' key.

**Comment by mrniket** [comment]
We aren't doing this anymore, not relevant.
