### ISSUE TITLE
Level builder - multiple lights

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#38]
We can only add one light on each sprite for now. We should perhaps think about a better way of adding lights instead of a simple toggle.

**Comment by danalex97** [comment]
This is quite tricky, I think. The back-end supports only one element in a cell; this is why we attach the light as part of the sprite. Attaching a list of lights to a sprite should probably do it - but then we need to navigate through all the lights and so on. 

If @j4mesholland and @mariaFernando don't think this will be necessary, we shouldn't implement it imho.

**Comment by mariaFernando** [comment]
I don't think there should be sprites with more than one light. For starters, sprites don't interact with lights so having one or two would have the same effect on the sprite itself. The only use I see for lights is really the effect on the 3D character, which then again will probably be too low res to react to light sources.
