### ISSUE TITLE
Level Builder - width and height components only seen when builder is wide

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo-unity#40]
Width and height fields are placed in a way such that it is only visible when on full screen and the window for the level builder needs to be quite wide for it.

![screenshot from 2017-09-08 10-08-18](https://user-images.githubusercontent.com/22431381/30204519-ade0a332-947d-11e7-9f9d-9a7f41f1eff3.png)

**Comment by ramonfmir** [comment]
True, we should talk to @j4mesholland and @mariaFernando about what layout they are going to use. I don't think is that worth it to spend time trying to make the editor tool too responsive.

**Comment by j4mesholland** [comment]
I wouldn't worry about making the builder responsive. As long as it works on a modern laptop screen.
