### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#41]
Often we try to load resources and assume that they're there, however that might not always be the case. Also, for instance the JSON format might be incorrect and everything will just fail without giving a very clear error message. There might be other cases in which better error handling is needed but these are the main two. Let's add our own assertions and error messages, it will make our lives easier.

**Comment by OlafSzmidt** [comment]
List of **occurances** that might need changing (for future ref):
- `LightSubMenu.cs` catching but not processing any error.

**Comment by danalex97** [comment]
@OlafSzmidt  For LightSubMenu, using [this](https://docs.unity3d.com/ScriptReference/EditorGUI.IntField.html) or [this](https://docs.unity3d.com/ScriptReference/EditorGUI.DelayedIntField.html) might not need any error handling.

**Comment by mrniket** [comment]
We aren't doing this anymore, not relevant.
