### ISSUE TITLE
Add style checks

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#42]
It would be nice to have style checks for C#.

**Comment by OlafSzmidt** [comment]
There isn't a style check for Unity conventions I'm afraid. We just have to follow what MonoDevelop is forcing us to do.

**Comment by danalex97** [comment]
@OlafSzmidt There are C# style check tools for visual studio, but I didn't find any style check tool to integrate with Travis either. I can write a python script for the usual stuff like spaces after function calls and so on...

**Comment by CelineBoudier** [comment]
We don't need stylechecks to work with Travis, codeclimate for instance runs independently when a PR is made.

**Comment by ramonfmir** [comment]
As an idea, we could also download visual studio on travis and use one of the plugins available for visual studio.

**Comment by danalex97** [comment]
@ramonfmir That's a good idea and would probably work. JetBrains also has a ![solution](https://www.jetbrains.com/help/resharper/Reference__Code_Style.html).

**Comment by CelineBoudier** [comment]
JetBrains are :heart_decoration:

**Comment by mrniket** [comment]
We aren't doing this anymore, not relevant.
