### ISSUE TITLE
Level builder - JSON not saved to file

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#46]
I'm pretty sure that the `ExportController` doesn't work.

**Comment by danalex97** [comment]
As in just saving to file or generating the JSON?

**Comment by danalex97** [comment]
I think we just lost this functionality during refactoring. Note that before we used to do it like this:

```csharp
[...]
ExportController.ExportFile (GetExportJson (levels));
[...]

private string GetExportJson(string[] levels)
	{
		string exportJson = ExportController.GetExportFromSerializer (
			new JSONSerializer(exportedLevelIdx != 0 ? levels[exportedLevelIdx] : null)
		);

		return exportJson;
}
```

You can see the commit [here](https://github.com/ocadotechnology/aimmo-unity/blob/019cdc70638ce279ccd43fcd893c08e6cf11b7a2/UnityProject/Assets/Editor/LevelGenerator/GUI/UtilityMenu.cs).

**Comment by danalex97** [comment]
To not run into this kind of issues while refactoring, we should add tests.

**Comment by CelineBoudier** [comment]
👍

**Comment by mrniket** [comment]
We aren't doing this anymore, not relevant.
