### ISSUE TITLE
Level Builder - Refactor LevelBuilderWindow

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo-unity#48]
- [ ] All the parts of the Level Builder are in separate files in the `Editor/GUI/Menus` directory. The generic file that renders the window, `LevelBuilderWindow.cs` is in `Editor/GUI` and contains some logic that should be moved to the `Menus` directory too.
- [ ] With PR #62 we introduced `GUIUtils.cs` which should take some logic out of menu's for re-use.

**Comment by mrniket** [comment]
We aren't doing this anymore, not relevant.
