### ISSUE TITLE
The green bar in the health bar does not appear

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#5]
The green and the red sprites that form the health bar are in the same layer and this leads to problems. When the avatar is created for the first time, it looks fine because of the order in which the sprites are added. However, when the isometric position is updated, the sorting order of the sprites in the children are also updated accordingly and this makes the red bar overlap the green bar completely sometimes.

**Comment by OlafSzmidt** [comment]
Fixed with #5?
