### ISSUE TITLE
Issue and PR templates

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo-unity#58]
To make our issues easier to understand, reproduce and read - I think we should make use of github's ability for templates.

We need to create files named as `PULL_REQUEST_TEMPLATE.md` and `ISSUE_TEMPLATE.md` in the root directory for our repo according to [this](https://github.com/blog/2111-issue-and-pull-request-templates) blog post. 

There's many open-source ones available to use already, such as [this](https://github.com/stevemao/github-issue-templates).

**Comment by j4mesholland** [comment]
We need to add this template to all the repo.

**Comment by faucomte97** [comment]
Not finished yet
