### ISSUE TITLE
WebGL Building: Improve build time

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo-unity#63]
Right now the build time, even for as little assets as we have imported, takes a very long time (10+ minutes). This is due to the fact that the build includes all the editor files which we ( @ramonfmir @danalex97 and I) believe are not needed.

Mentioned in #26. 

I know movement of files in and out of the Editor folder can omit them from building... but don't think this is the best option. 

This is truly dependent on the fact if we manage (or decide to) split the editor from the rest of the code. Personally I don't think it's possible. This is in issue #27.

Article that may help: [here](https://support.unity3d.com/hc/en-us/articles/208456906-Excluding-Scripts-and-Assets-from-builds).

**Comment by mrniket** [comment]
Not a priority, closing.
