### ISSUE TITLE
CI not running tests any more

### ISSUE THREAD

**Issue by danalex97** [ocadotechnology/aimmo-unity#67]
We had at some point a version that was running some tests on Travis. 
Maybe we should cherry-pick that from the travis branch?

@ramonfmir @OlafSzmidt @CelineBoudier

**Comment by CelineBoudier** [comment]
Testing sounds good I'd say ;)

**Comment by OlafSzmidt** [comment]
I've never seen them before. Wonder if they are obsolete now:|

**Comment by danalex97** [comment]
I don't think so. We didn't change much in `Assets/Scripts`.

**Comment by OlafSzmidt** [comment]
@danalex97 - We haven't, no.

**Comment by mrniket** [comment]
Still relevant but not a priority.
